FROM mcr.microsoft.com/dotnet/sdk:6.0
RUN apt-get update \
    && apt-get -y install --no-install-recommends netcat net-tools dnsutils nginx gnupg2 tcpdump jq ncat libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev libasound2 npm python3-pip

# To install k6
#RUN gpg -k
#RUN gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
#RUN echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | tee /etc/apt/sources.list.d/k6.list

#RUN apt-get update \
#    && apt-get -y install --no-install-recommends k6

RUN npm install --global carbonyl
RUN pip3 install flask requests
